// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repositories

import (
	"database/sql"
)

type Order struct {
	ID         uint64       `json:"id"`
	CustomerID int64        `json:"customer_id"`
	TotalPrice int32        `json:"total_price"`
	Status     string       `json:"status"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

type OrderItem struct {
	ID          uint64       `json:"id"`
	OrderID     int64        `json:"order_id"`
	ProductID   int64        `json:"product_id"`
	ProductName string       `json:"product_name"`
	Price       int32        `json:"price"`
	Quantity    int32        `json:"quantity"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Product struct {
	ID        uint64       `json:"id"`
	Name      string       `json:"name"`
	Price     int32        `json:"price"`
	Quantity  int32        `json:"quantity"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
