// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repositories

import (
	"context"
	"database/sql"
)

const createOrder = `-- name: CreateOrder :execresult
INSERT INTO
    orders (customer_id, total_price, status)
VALUES
    (?, ?, ?)
`

type CreateOrderParams struct {
	CustomerID int64  `json:"customer_id"`
	TotalPrice int32  `json:"total_price"`
	Status     string `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrder, arg.CustomerID, arg.TotalPrice, arg.Status)
}

const createOrderItems = `-- name: CreateOrderItems :execresult
INSERT INTO
    order_items (
        order_id,
        product_id,
        product_name,
        price,
        quantity
    )
VALUES
    (?, ?, ?, ?, ?)
`

type CreateOrderItemsParams struct {
	OrderID     int64  `json:"order_id"`
	ProductID   int64  `json:"product_id"`
	ProductName string `json:"product_name"`
	Price       int32  `json:"price"`
	Quantity    int32  `json:"quantity"`
}

func (q *Queries) CreateOrderItems(ctx context.Context, arg CreateOrderItemsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrderItems,
		arg.OrderID,
		arg.ProductID,
		arg.ProductName,
		arg.Price,
		arg.Quantity,
	)
}

const createProduct = `-- name: CreateProduct :execresult
INSERT INTO
    products (name, price, quantity)
VALUES
    (?, ?, ?)
`

type CreateProductParams struct {
	Name     string `json:"name"`
	Price    int32  `json:"price"`
	Quantity int32  `json:"quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProduct, arg.Name, arg.Price, arg.Quantity)
}

const deleteProducts = `-- name: DeleteProducts :exec
DELETE FROM products
WHERE
    id = ?
`

func (q *Queries) DeleteProducts(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteProducts, id)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT
    id, customer_id, total_price, status, created_at, updated_at
FROM
    orders
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetOrder(ctx context.Context, id uint64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT
    id, name, price, quantity, created_at, updated_at
FROM
    products
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetProduct(ctx context.Context, id uint64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT
    id, customer_id, total_price, status, created_at, updated_at
FROM
    orders
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.TotalPrice,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    id, name, price, quantity, created_at, updated_at
FROM
    products
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductQty = `-- name: UpdateProductQty :execresult
UPDATE products
SET
    quantity = ?
WHERE
    id = ?
`

type UpdateProductQtyParams struct {
	Quantity int32  `json:"quantity"`
	ID       uint64 `json:"id"`
}

func (q *Queries) UpdateProductQty(ctx context.Context, arg UpdateProductQtyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProductQty, arg.Quantity, arg.ID)
}
