// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repositories

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error)
	CreateOrderItems(ctx context.Context, arg CreateOrderItemsParams) (sql.Result, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error)
	DeleteProducts(ctx context.Context, id uint64) error
	GetOrder(ctx context.Context, id uint64) (Order, error)
	GetProduct(ctx context.Context, id uint64) (Product, error)
	ListOrders(ctx context.Context) ([]Order, error)
	ListProducts(ctx context.Context) ([]Product, error)
	UpdateProductQty(ctx context.Context, arg UpdateProductQtyParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
